services:
  - type: web
    name: hikeyz-api
    runtime: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: false
